In [1]:
import pandas as pd
import numpy as np

In [2]:
country = pd.read_csv("EdStatsCountry.csv")

In [3]:
country

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,Unnamed: 31
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,...,NaN,2010,NaN,NaN,Yes,NaN,NaN,2012.0,NaN,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2012.0,2000,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,XKX,Kosovo,Kosovo,Republic of Kosovo,NaN,Euro,"Kosovo became a World Bank member on June 29, ...",Europe & Central Asia,Lower middle income,KV,...,General Data Dissemination System (GDDS),2011,NaN,"Integrated household survey (IHS), 2011",NaN,NaN,NaN,NaN,NaN,NaN
237,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Based on official government statistics and In...,Middle East & North Africa,Lower middle income,RY,...,General Data Dissemination System (GDDS),2004,"Demographic and Health Survey (DHS), 2013","Expenditure survey/budget survey (ES/BS), 2005",NaN,NaN,2006.0,2012.0,2005,NaN
238,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Fiscal year end: March 31; reporting period fo...,Sub-Saharan Africa,Upper middle income,ZA,...,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey (DHS), 2003; Wor...","Expenditure survey/budget survey (ES/BS), 2010",NaN,2007,2010.0,2012.0,2000,NaN
239,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,National accounts data have rebased to reflect...,Sub-Saharan Africa,Lower middle income,ZM,...,General Data Dissemination System (GDDS),2010,"Demographic and Health Survey (DHS), 2013","Integrated household survey (IHS), 2010",NaN,2010. Population and Housing Census.,NaN,2011.0,2002,NaN
240,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,General Data Dissemination System (GDDS),2012,"Demographic and Health Survey (DHS), 2010/11","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2012.0,2002,NaN

In [4]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 32 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country Code                                       241 non-null    object
 1   Short Name                                         241 non-null    object
 2   Table Name                                         241 non-null    object
 3   Long Name                                          241 non-null    object
 4   2-alpha code                                       238 non-null    object
 5   Currency Unit                                      215 non-null    object
 6   Special Notes                                      145 non-null    object
 7   Region                                             214 non-null    object
 8   Income Group                                       214 non-null    object
 9   WB-2 code                                          240 non-null    object
 10  National accounts base year                        205 non-null    object
 11  National accounts reference year                   32 non-null     float64
 12  SNA price valuation                                197 non-null    object
 13  Lending category                                   144 non-null    object
 14  Other groups                                       58 non-null     object
 15  System of National Accounts                        215 non-null    object
 16  Alternative conversion factor                      47 non-null     object
 17  PPP survey year                                    145 non-null    object
 18  Balance of Payments Manual in use                  181 non-null    object
 19  External debt Reporting status                     124 non-null    object
 20  System of trade                                    200 non-null    object
 21  Government Accounting concept                      161 non-null    object
 22  IMF data dissemination standard                    181 non-null    object
 23  Latest population census                           213 non-null    object
 24  Latest household survey                            141 non-null    object
 25  Source of most recent Income and expenditure data  160 non-null    object
 26  Vital registration complete                        111 non-null    object
 27  Latest agricultural census                         142 non-null    object
 28  Latest industrial data                             107 non-null    float64
 29  Latest trade data                                  185 non-null    float64
 30  Latest water withdrawal data                       179 non-null    object
 31  Unnamed: 31                                        0 non-null      float64
dtypes: float64(4), object(28)
memory usage: 60.4+ KB

In [5]:
country = country[['Table Name','Region','Income Group','Special Notes']]

In [6]:
country.rename(columns = {'Table Name':'Country Name'}, inplace = True)

C:\Users\linae\AppData\Local\Temp\ipykernel_3436\565484246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  country.rename(columns = {'Table Name':'Country Name'}, inplace = True)

In [7]:
%store country

Stored 'country' (DataFrame)

,Country Name,Region,Income Group,Special Notes
0,Aruba,Latin America & Caribbean,High income: nonOECD,SNA data for 2000-2011 are updated from offici...
1,Afghanistan,South Asia,Low income,Fiscal year end: March 20; reporting period fo...
2,Angola,Sub-Saharan Africa,Upper middle income,"April 2013 database update: Based on IMF data,..."
3,Albania,Europe & Central Asia,Upper middle income,NaN
4,Andorra,Europe & Central Asia,High income: nonOECD,NaN
...,...,...,...,...
236,Kosovo,Europe & Central Asia,Lower middle income,"Kosovo became a World Bank member on June 29, ..."
237,"Yemen, Rep.",Middle East & North Africa,Lower middle income,Based on official government statistics and In...
238,South Africa,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...
239,Zambia,Sub-Saharan Africa,Lower middle income,National accounts data have rebased to reflect...
240,Zimbabwe,Sub-Saharan Africa,Low income,Fiscal year end: June 30; reporting period for...